Set memory and time limits for performance tests
Set memory limit for performance tests to (16 Gb - 256 Kb) so that
the entire runner won't get killed
Set time limit to 1.5 hour, just in case

diff --git a/.github/workflows/performance-tests.yml b/.github/workflows/performance-tests.yml
--- a/.github/workflows/performance-tests.yml
+++ b/.github/workflows/performance-tests.yml
@@ -99,13 +99,29 @@ jobs:
 
       - name: Test
         working-directory: ${{github.workspace}}/build/target
+        # Disable '-e' in this step
+        shell: bash --noprofile --norc -o pipefail {0}
         run: |
+          # 256 Kb should be enough to exit gracefully
+          MEMORY_LIMIT="$((16 * 1024 - 256))"
+          TIME_LIMIT='5400' # 1.5 hours
+
           if [[ -a 'baseline.json' ]]; then
-            ./Desbordante.benchmark --baseline ${{ github.workspace }}/baseline.json \
+            systemd-run --user --scope -p MemoryMax="$MEMORY_LIMIT" -p RuntimeMaxSec="$TIME_LIMIT" \
+              ./Desbordante.benchmark --baseline ${{ github.workspace }}/baseline.json \
               --output ${{ github.workspace }}/curr-results.json
           else
-            ./Desbordante.benchmark --output ${{ github.workspace }}/curr-results.json
+            systemd-run --user --scope -p MemoryMax="$MEMORY_LIMIT" -p RuntimeMaxSec="$TIME_LIMIT" \
+              ./Desbordante.benchmark --output ${{ github.workspace }}/curr-results.json
           fi
+          EXIT_CODE="$?"
+
+          if [ "$EXIT_CODE" -eq 137 ]; then
+            echo '::error::Out of memory'
+          elif [ "$EXIT_CODE" -eq 143 ]; then
+            echo '::error::Killed by timeout'
+          fi
+          exit "$EXIT_CODE"
 
       # All next steps should be ran even if this one has failed
       # Some of them may fail in that case, but it's not a problem
